# Generated by Django 4.1.4 on 2022-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_alter_hedar_img_alter_newarrivals_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedar',
            name='img',
            field=models.ImageField(upload_to='hedarimg'),
        ),
        migrations.AlterField(
            model_name='newarrivals',
            name='img',
            field=models.ImageField(upload_to='newArrivalsimg'),
        ),
        migrations.AlterField(
            model_name='newarrivalssecond',
            name='img',
            field=models.ImageField(upload_to='newArrivalsSecondimg'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='Img',
            field=models.ImageField(upload_to='newProductimg'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='img',
            field=models.ImageField(upload_to='newsletterimg'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img',
            field=models.ImageField(upload_to='Slideimg'),
        ),
        migrations.AlterField(
            model_name='toprated',
            name='img',
            field=models.ImageField(upload_to='TopRatedimg'),
        ),
        migrations.AlterField(
            model_name='topratedsecond',
            name='img',
            field=models.ImageField(upload_to='TopRatedSecondimg'),
        ),
        migrations.AlterField(
            model_name='trending',
            name='img',
            field=models.ImageField(upload_to='trendingimg'),
        ),
        migrations.AlterField(
            model_name='trendingsecond',
            name='img',
            field=models.ImageField(upload_to='trendingSecondimg'),
        ),
    ]
